module.exports = {
  '#text':        true,
  '#jsx':         true,
  '#prop':        true,

  'span':         true,
  'view':         true,
  'scroll—view':  true,
  'swiper':       true,
  'icon':         true,
  'movable-area': true,
  'cover-view':   true,
  'icon':         true,
  'text':         true,
  'rich-text':    true,
  'progress':     true,
  'button':       true,
  'checkbox':     true,
  'form':         true,
  'input':        true,
  'label':        true,
  'picker':       true,
  'picker-view':  true,
  'radio':        true,
  'slider':       true,
  'switch':       true,
  'textarea':     true,
  'navigator':    true,
  'audio':        true,
  'image':        true,
  'video':        true,
  'map':          true,
  'cnavas':       true,
  'open-data':    true,
  'contact-button': true,
  'template':     true,
  'block':        true
}